import type { LookupOptions, Option } from "./types";

/**
 * A bundled copy of GET /api/lookup/options, so the form renders in full
 * without a backend. The backend only matters on final submit; when it is
 * reachable, its response is merged over this at load.
 *
 * Mirrors loan-backend/src/modules/lookup/lookup.controller.ts - keep the two
 * in step when an option changes.
 */

const opts = (labels: Record<string, string>): Option[] =>
  Object.entries(labels).map(([value, label]) => ({ value, label }));

export const DEFAULT_OPTIONS: LookupOptions = {
  loanAmount: { min: 2000, max: 50000, step: 500, default: 10000 },
  loanPurposes: opts({
    debt_consolidation: "Debt Consolidation",
    emergency_expenses: "Emergency Expenses",
    medical_expenses: "Medical Expenses",
    dental_expenses: "Dental Expenses",
    home_improvement: "Home Improvement",
    auto_repair: "Auto Repair",
    moving_expenses: "Moving Expenses",
    wedding_expenses: "Wedding Expenses",
    vacation: "Vacation",
    education: "Education",
    rent_or_utilities: "Rent or Utilities",
    major_purchase: "Major Purchase",
    childcare_expenses: "Childcare Expenses",
    funeral_expenses: "Funeral Expenses",
    tax_payments: "Tax Payments",
    business_expenses: "Business Expenses",
    other_personal_expenses: "Other Personal Expenses",
  }),
  loanTerms: [12, 24, 36, 48].map((t) => ({ value: t, label: `${t} months` })),
  suffixes: opts({
    none: "None",
    jr: "Jr",
    sr: "Sr",
    ii: "II",
    iii: "III",
    iv: "IV",
  }),
  states: opts({
    AL: "Alabama",
    AK: "Alaska",
    AZ: "Arizona",
    AR: "Arkansas",
    CA: "California",
    CO: "Colorado",
    CT: "Connecticut",
    DE: "Delaware",
    FL: "Florida",
    GA: "Georgia",
    HI: "Hawaii",
    ID: "Idaho",
    IL: "Illinois",
    IN: "Indiana",
    IA: "Iowa",
    KS: "Kansas",
    KY: "Kentucky",
    LA: "Louisiana",
    ME: "Maine",
    MD: "Maryland",
    MA: "Massachusetts",
    MI: "Michigan",
    MN: "Minnesota",
    MS: "Mississippi",
    MO: "Missouri",
    MT: "Montana",
    NE: "Nebraska",
    NV: "Nevada",
    NH: "New Hampshire",
    NJ: "New Jersey",
    NM: "New Mexico",
    NY: "New York",
    NC: "North Carolina",
    ND: "North Dakota",
    OH: "Ohio",
    OK: "Oklahoma",
    OR: "Oregon",
    PA: "Pennsylvania",
    RI: "Rhode Island",
    SC: "South Carolina",
    SD: "South Dakota",
    TN: "Tennessee",
    TX: "Texas",
    UT: "Utah",
    VT: "Vermont",
    VA: "Virginia",
    WA: "Washington",
    WV: "West Virginia",
    WI: "Wisconsin",
    WY: "Wyoming",
  }),
  residenceTenure: opts({
    under_6_months: "Under 6 months",
    "6_11_months": "6-11 months",
    "1_2_years": "1-2 years",
    "3_5_years": "3-5 years",
    "5_plus_years": "5+ years",
  }),
  housingStatuses: opts({
    rent: "Rent",
    own_with_mortgage: "Own with mortgage",
    own_outright: "Own outright",
    living_with_family_or_friends: "Living with family or friends",
    military_housing: "Military housing",
    other: "Other",
  }),
  housingStatusesRequiringPayment: ["rent", "own_with_mortgage"],
  employmentStatuses: opts({
    employed_full_time: "Employed - Full Time",
    employed_part_time: "Employed - Part Time",
    self_employed: "Self-Employed",
    active_military: "Active Military",
    retired: "Retired",
    disability: "Disability",
    social_security: "Social Security",
    unemployment_benefits: "Unemployment Benefits",
    other_benefits: "Other Benefits",
    student: "Student",
    not_currently_employed: "Not Currently Employed",
  }),
  employerFieldStatuses: [
    "employed_full_time",
    "employed_part_time",
    "self_employed",
    "active_military",
  ],
  incomeTypes: opts({
    employment: "Employment",
    self_employment: "Self-Employment",
    retirement_or_pension: "Retirement or Pension",
    social_security: "Social Security",
    disability: "Disability",
    unemployment: "Unemployment",
    other: "Other",
  }),
  derivedIncomeType: {
    employed_full_time: "employment",
    employed_part_time: "employment",
    self_employed: "self_employment",
    active_military: "employment",
    retired: "retirement_or_pension",
    disability: "disability",
    social_security: "social_security",
    unemployment_benefits: "unemployment",
    other_benefits: null,
    student: null,
    not_currently_employed: null,
  },
  jobTenure: opts({
    under_3_months: "Under 3 months",
    "3_5_months": "3-5 months",
    "6_11_months": "6-11 months",
    "1_2_years": "1-2 years",
    "3_5_years": "3-5 years",
    "5_plus_years": "5+ years",
  }),
  payFrequencies: opts({
    weekly: "Weekly",
    every_two_weeks: "Every two weeks",
    twice_a_month: "Twice a month",
    monthly: "Monthly",
    irregular: "Irregular",
  }),
  accountTypes: opts({ checking: "Checking", savings: "Savings" }),
  accountStatuses: opts({ positive: "Positive", negative: "Negative" }),
  accountAges: opts({
    under_6_months: "Under 6 months",
    "1_year": "1 Year",
    "2_years": "2 Years",
    "3_years": "3 Years",
    "4_years": "4 Years",
    "5_plus_years": "5 Years +",
  }),
  regBNotice:
    "Alimony, child support, or separate maintenance income need not be revealed if you do not wish to have it considered as a basis for repaying this obligation.",
};
